### ISSUE TITLE
Version 1.2.1 - Problem in loading module

### ISSUE THREAD

**Issue by qlikbez** [koola/pix-diff#51]
I've referenced the latest version 1.2.1 from the npm repository but it breaks the node module loading, i think could be some syntax problem, or it has no compatibility with babel (EC6), message:

[16:40:22] E/launcher - Error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] ([...]node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

This problem is not present in version 1.2.0

**Comment by wswebcreation** [comment]
Which version of node are you on? I expect < 6


I found out that png-image (dependency), that was upgraded to a newer version, caused this problem in combination with Node < 6.

If you upgrade (save upgrade with NVM) to 6.9 or latest stable of 7 the issue won't popup.

Hope it helps

Grtz

Wim

**Comment by qlikbez** [comment]
yes correct, thanks!

**Comment by wswebcreation** [comment]
Don't close the issue. It's a "breaking change" in png-image that should be fixed

**Comment by koola** [comment]
Sorry, this is my bad for not updating the engine enforcement version in `package.json`. The reason is due to using ES6 defaults, which according to [node.green](http://node.green/) requires `node >= 6.9.2`

**Comment by qualityshepherd** [comment]
I was just about to write this bug... so looks like I need to update node.

**Comment by wswebcreation** [comment]
Still think it's a "bug" 😁, or a new release because of dependency bumps

**Comment by qualityshepherd** [comment]
Yeah, no... not a bug, but rather a breaking change.

**Comment by koola** [comment]
I've fixed the semver, closing this now.

**Comment by wswebcreation** [comment]
Are you also going to revert the breaking changes from 1.2.2 to a new version 1.2.3?

Otherwise 1.2.2 == 2.0.0 and people still have problems when depending ^1.2.0
